language: node_js
node_js:
- '7'
- '6'
- '5'
- '4'
deploy:
  provider: npm
  email: code@oledid.com
  api_key:
    secure: kTmUMWSUQb62zSMyCCAs0wzWshmgdvxEl65lG7EjURBID+pXr8MvpRPB4ozoFywxjpr5cl4P0M99mVvG8gev0h3aQFAyHxDW+16FYjbv+MDS447Kc7QxKUw7GPllzZV/tga4oxpwPTKdv06DGgB/4d3gnqJnnHEVv7AB26cwugQqJzjdMwqGwi/11cdoF4T/EGof0aR/FQu2n9iiSSSAm7J3kNIGIHjdW3g/C2+ZnUtXgOWpp1sSfz2V+ddyRtlLnYyrA1EJ5V+Jgs5hOddd26SLCp3gZ27Bl3ofu6B47eW2jJM3ekHafHmYcmDBITfqj3MIdaLxf9Ent1BaqFIIlrnK4txfSH0KsBN++g/Bj/dkSeyYvf5gkcifDpAodvRfKBm/5GxBs8vPhlTaDpV8/XR9VUgpQWiiWJzWf4yhUpnHWYRqsjliceGS8PURSwuOc3qLEb7TFm2r5uvpD3b2krB3kZ//VLA0aXrXliHE9KbezGkW/XpZkBewen9VVZCxZzNqkMI1oquPZwV+C5dSJdGskl36q9A+ZCr0S5Doycb3qRH+tJDPF06w0hLjxo39gMLyM4cJ9GEVM+T79XC3iHhumv63t81PpQBpDpRtPK11F2KE2Z1thm/DCItnOcumh/rGbBfitqr9YCyB0f6YPFcPdJQtg/VYAh/tkZJAtOg=
